# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

language: objective-c
before_install:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet # Since Travis is not always on latest version
- pod install --project-directory=Xcode/Testing2
install:
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
- set -o pipefail && xcodebuild test -workspace Xcode/Testing2/XMPPFrameworkTests.xcworkspace -scheme XMPPFrameworkTests -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 6,OS=8.1' | xcpretty -c
